### ISSUE TITLE
Sample code for positioning the described object after pictures and language

### ISSUE THREAD

**Issue by 3202336152** [Toneyaya/CoTDet#1]
Thank you so much for your excellent work!Could you please provide the example code in the paper that decomposes the task by inputting pictures and language and then locating the corresponding area?

**Comment by Toneyaya** [comment]
Sorry, I don't quite understand. 
Would you like the code to build the knowledge base via MLCoT?

**Comment by 3202336152** [comment]
Gracias por su respuesta. Lo que quiero decir es que en base al modelo entrenado, introduciendo la imagen y la descripción lingüística, se puede detectar la región correspondiente, ¿se da el código para una función como esta?

**Comment by 3202336152** [comment]
Thank you for your reply! What I mean is that based on the trained model, the corresponding region can be detected by inputting the image and language description, is the code for a function like this given?

**Comment by 3202336152** [comment]
Thank you for your reply! What I mean is that based on the trained model, the corresponding region can be detected by inputting the image and language description, is the code for a function like this given?Similar to this example you gave.
![微信图片_20240331224026](https://github.com/SooLab/CoTDet/assets/50447745/b1410364-98a1-4fbb-8ab4-4d1bf7cbbf4b)

**Comment by Toneyaya** [comment]
While there isn’t a specific demo available yet, we acknowledge that our current model doesn’t prioritize generalization ability. If you attempt to apply it to tasks beyond its training dataset, the results may not meet your expectations.

**Comment by 3202336152** [comment]
Is there no visual result graph after Evaluation is executed? What is the significance of instances_predictions.pth model?
